### ISSUE TITLE
Energy lost

### ISSUE THREAD

**Issue by hodo1962** [RogueLogix/BiggerSeries#26]
Reactor loses all stored energy and goes offline after relogging into the game. 
This also happens when warping to the Nether or End and back (with the  help of the mod "Ma-Essentials")

Edit: It also loses all stored fuel.

Minecraft version:    1.16.3
Forge:    34.1.25
Mod version:   biggerreactors-1.16.3-0.2.0-beta
                       phosphophyllite-1.16.3-0.0.5-beta

**Comment by RogueLogix** [comment]
Is this repeatable? If so, if you could provide a screenshot of the reactor with chunks shown (F3 + G), that would be very helpful in my debugging this.

**Comment by RogueLogix** [comment]
seems to be happening on the server i play on too, ill see if i can get it fixed.

**Comment by hodo1962** [comment]
Sorry for my late answer. The bug is repeatable, but i have no screens or logs.
I've made a fallback to the previous versions. The problem does not appear with biggerreactors-1.16.3-0.1.9-beta and
phosphophyllite-1.16.3-0.0.4-beta.

**Comment by RogueLogix** [comment]
Can you give details on how it's repeatable? Ie: chunk alignment of reactor, how it's loaded/unloaded.

**Comment by hodo1962** [comment]
I've tested a bit. After installing a chunkloader (chunkloaders), this bug doesn't appear anymore. 
After removing the chunkloader and relogging, the bug was back again.
Here is a screen from the reactor location. It is placed in the border of two chunks. This might not
the best place.

![2020-10-29_20 21 55](https://user-images.githubusercontent.com/69686049/97623220-a1776280-1a25-11eb-8ce9-2795e967adcb.png)

Here is a list of the mod i use:
[✔️] ava-1.5.0
  [✔️] BetterCaves-1.16.2-1.0.4
  [✔️] BetterMineshaftsForge-1.16.2-1.0.1
  [❌] biggerreactors-1.16.3-0.1.9-beta.jar (disabled)
  [✔️] biggerreactors-1.16.3-0.2.0-beta
  [✔️] BiomesOPlenty-1.16.3-12.0.0.409-universal
  [✔️] chunkloaders-1.1.0-mc1.16.3
  [✔️] collective-1.16.3-1.51
  [✔️] connectedglass-1.0.6-mc1.16.3
  [✔️] ContentTweaker-1.16-1.0.0.develop.8
  [✔️] CraftTweaker-1.16.3-7.0.0.40
  [✔️] Cucumber-1.16.3-4.1.2
  [✔️] curios-forge-1.16.3-4.0.2.0
  [✔️] dankstorage-3.11
  [✔️] extradisks-1.16.3-1.3.3
  [✔️] FluxNetworks-1.16.3-6.0.0.3
  [✔️] ftb-gui-library-1603.1.1.24
  [✔️] gravestone-1.16.3-1.0.2
  [✔️] immersive-portals-0.7-mc1.16.3-forge
  [✔️] industrial-foregoing-1.16.3-3.1.1-a834e76
  [✔️] invtweaks-1.16.2-1.0.0
  [✔️] jei-1.16.3-7.6.0.49
  [✔️] LargeFluidTank-16.0.6
  [✔️] Lollipop-1.16.3-3.2.2
  [✔️] Ma-Essentials-1.16.3-3.4.0
  [✔️] mcjtylib-1.16-5.0.11
  [✔️] Mekanism-1.16.3-10.0.15.441
  [✔️] MekanismAdditions-1.16.3-10.0.15.441
  [✔️] MekanismGenerators-1.16.3-10.0.15.441
  [✔️] MekanismTools-1.16.3-10.0.15.441
  [✔️] metalbarrels-3.3a
  [✔️] mineralchance_1.16.3-1.0
  [✔️] mininggadgets-1.6.0
  [✔️] movingelevators-1.2.21-mc1.16.3
  [✔️] MysticalAgradditions-1.16.3-4.1.0
  [✔️] MysticalAgriculture-1.16.3-4.1.1
  [✔️] MysticalCustomization-1.16.3-2.1.0
  [✔️] NoFog-1.16.2-Forge-b1
  [❌] phosphophyllite-1.16.3-0.0.4-beta.jar (disabled)
  [✔️] phosphophyllite-1.16.3-0.0.5-beta
  [✔️] reap-1.16.3-1.0.2
  [✔️] refinedstorage-1.9.7
  [✔️] refinedstorageaddons-0.7.2
  [✔️] rftoolsbase-1.16-2.0.6
  [✔️] rftoolsbuilder-1.16-3.0.8
  [✔️] rftoolspower-1.16-3.0.8
  [✔️] rftoolsutility-1.16-3.0.11
  [✔️] rsrequestify-1.16.3-2.0
  [✔️] ScalableCatsForce-2.13.3-build-3-with-library
  [✔️] SolarFluxReborn-1.16.3-16.1.1
  [✔️] staretilltheygrow-1.16.3-1.0.2
  [✔️] theoneprobe-1.16-3.0.4-beta
  [✔️] titanium-1.16.3-3.1.0
  [✔️] TrampleStopper-2.4.3
  [✔️] trashcans-1.0.3-mc1.16.3
  [✔️] u_team_core-1.16.3-3.1.10.183
  [✔️] useful_backpacks-1.16.3-1.11.6.83
  [✔️] Xaeros_Minimap_20.25.1_Forge_1.16.3
  [✔️] XaerosWorldMap_1.11.0_Forge_1.16.3
  [✔️] xnet-1.16-3.0.7

**Comment by RogueLogix** [comment]
is this in single player, or a dedicated server?

**Comment by RogueLogix** [comment]
Was able to reproduce with identical reactor configuration after moving out of spawn chunks, above commit does fix this specific issue. Phosphophyllite may get mad on the log when you update, and it may poke its head on first launch, should be fixed from then on though. If singleplayer you can test the attached files, just be careful with them, as they don't have correct version checking to *nicely* yell at you for using the wrong versions (use them as a pair), they will crash if used with an incompatible version.

[reobfJar.zip](https://github.com/RogueLogix/BiggerSeries/files/5463740/reobfJar.zip)

**Comment by hodo1962** [comment]
I've tested the attached files in single player. 
The bug is still there. Without a chunk loader, the reactor loses it's fuel and stored power.

**Comment by RogueLogix** [comment]
Ok, i believe i found the cause of this, a fancy new bug, that looks very similar

To verify that i found the correct bug, can you check that the reactor only resets itself if you click off of minecraft while the world is loading, causing minecraft to pause immediately. Should exhibit the bug regardless of distance to reactor

Regardless if this is the correct bug, this was causing a bug where the game would save the reactor before it has a chance to read its values, resulting in a default reactor being read from, and so the values reset after the game is unpaused, as i cache the values.

**Comment by hodo1962** [comment]
I've tested a bit:
1. I went to the nether and back through a portal (immersive portals). Reactor stayed stable.
2. I teleported to the nether and back: Reactor stayed stable.
3. I teleported 2000 blocks away and back: Reactor stayed stable.
4. I teleported 2000 blocks away and logged off and on: Reactor stayed stable.
5. I ended Minecraft the hard way (simply closing the window): Reactor stayed stable.
6. I teleported to the nether and back. While teleporting back, i logged off. This causes the reactor to reset. So it seems you've found the the bug.

**Comment by RogueLogix** [comment]
6 still does or did but now doesn't cause the reactor to reset?

**Comment by hodo1962** [comment]
I've tested that with the new version and it seems to work fine - no reactor reset. 
I can not test it more often cause the halloween kids permanently ring the door bell for sweats.

**Comment by RogueLogix** [comment]
alright, im going to close the issue then. if it happens again open a new issue.
